### ISSUE TITLE
Example for websocketd/web-vmstats in Docker behind nginx proxy and basic auth

### ISSUE THREAD

**Issue by srault95** [joewalnes/websocketd#109]
https://github.com/srault95/docker-websocketd

Thanks.

**Comment by joewalnes** [comment]
Sorry, I'm not sure what this issue is for. Can you clarify?

**Comment by srault95** [comment]
sorry, it was not a question.
This is a demonstration of websocketd / web-vmstats on Docker.

**Comment by asergeyev** [comment]
I'm also not sure where we should go with it. 

It's definitely an example of use. But there is little to demonstrate websocketd, mostly showcase for docker and web-vmstats.... And also somewhat not obvious use, since containerizing vmstats gives you somewhat limited view of the parent system.

We might get back to dockerized websocketd topics later in wiki, as we start seeing people talking about problems where solution is requiring those two combined... So far it's not the case. 

I'm also sure that in meanwhile, people who would search for keywords "docker" and "websocketd" would find your code and will appreciate that your work is going to provide good hints to them.

I'll close the issue soon, but even on closed ticket we could continue this discussion. I'm open to conversation. I'd bet Joe is also willing to listen.

**Comment by srault95** [comment]
you are right, I think in the demonstration, the only important point is to place websocketd behind nginx with authentication.

**Comment by asergeyev** [comment]
Thanks for the comment and for your understanding.
