### ISSUE TITLE
Execute wrapped process once and exit

### ISSUE THREAD

**Issue by mattbaird** [joewalnes/websocketd#132]
I think maybe this issue has been filed before, but it got closed and I don't know why - it seems like a valid feature with a good use case.

I have a command line installer that reads a config file and installs some software.

I am writing a web UI to make the installer more friendly. My installer web UI collects information from the user, generates the config file and then executes the existing command line installer.

The command line installed emits a standardized set of log messages that I want to deliver to the web UI via websocketd so I can parse and display a progress bar with appropriate messages. This is similar to the Cloudera Hadoop installer.

The ReconnectingWebSocket library reconnects to the web socket every time it gets a DISCONNECT signal which triggers websocketd to rerun the wrapped process. This would be a PITA to have the install re-run. I would like it to run once and exit. Since I'm wrapping websocketd in another more featured webby framework (revel in this case). 

Now I guess i could stop using ReconnectingWebSocket, but if the websocket gets called for any reason after it exits, it will restart the install.

I propose (and will develop a PR for, if you ok it) a --runOnce param which will run the process once and then quit.

**Comment by joewalnes** [comment]
Hi @mattbaird

Thanks for the offer of help. We've discussed this scenario a few times, see #50, #84, #95 and in particular https://github.com/joewalnes/websocketd/issues/95#issuecomment-63680034

While we could easily add a flag for the single use-case you describe, there are lots of edge cases that arise from it, such as:

- what happens to output that is generated by the process in between reconnection attempts? is it discarded, stored somewhere, replayed upon connection, etc?
- what if a client never reconnects? how long should the process live for?
- what if multiple clients connect? is the output sent to all processes? do clients need to catchup on missed data?
- how does the process authenticate separate clients that are connected? (with one connection per process websocketd sets headers in environment variables, but this doesn't work with multiple connection per process)
- what happens if the process dies? how does a client attempt to restart it?
- when does the process start? should it happen when websocketd starts, or when the first connection happens?
- if multiple clients are sending data to the process, how can the process know which client its coming from?

These are things that your use-case may not need to worry about, but others will. Rather than designing for a single use-case I would prefer to think of websocketd as one of the building blocks, and other blocks can be added to support different cases.

---

To implement what you want, you can create a program that wraps your installer and launch the wrapper from websocketd. The wrapper would run for each connection so it would be its responsibility to launch the actual installer process if needed, replay log files, provide any access controls, etc. You could do this as a one-off script for your own needs, or build a separate tool that may be of interest to the wider websocketd community.
