### ISSUE TITLE
support for connect to backend ip+port ?

### ISSUE THREAD

**Issue by jbardu** [joewalnes/websocketd#153]
Perhaps this sounds strange. but it would be useful for me at least to have websocketd not fork a program and run it for one connection, but simply connect to a given ip address and port, most likely 127.0.0.1 or a unix socket.

So for example listening on that port might be an event driven I/O capable process that just wants to talk to new clients via read and write with having to worry about all the web socket stuff, and it might be able to handle 65000 clients, or more with more than one IP address.

So clients <---> nginx <---> websocketd <---> event driven single thread process ?
or clients <---> websocketd <---> event driven single threaded process

Does this make sense or am I missing something.

**Comment by asergeyev** [comment]
using netcat?

   websocket --address 0.0.0.0 --port 12345 nc HOST PORT

**Comment by asergeyev** [comment]
Only would not do mux/demux thing for you, you got to do something differently if you need it... 

(we discussed this many times, check closed tickets,... )

**Comment by jbardu** [comment]
ok will check thanks.
so although websocketd is very fast, (it is much faster than python with a websocket library, I find)
scaling to lots of simultaneous clients requires lots of simultaneous child processes.

**Comment by jbardu** [comment]
Wait I don't care about mux demux -- like many clients one vmstat output.

I want many clients, one server with i/o event driven handling (one thread), but of course server is talking differently to each client, knowing it by port number and whatever protocol I use.

so netcat works -- but it doesn't work if I have 10,000 clients I don't want 10,000 nc processes.

Why can't websocketd, which already handles lots of clients, do what nc would be doing?

**Comment by aj664** [comment]
i've written a websocket server, from scratch.   it's not rocket science 
to get a dozen socket server working.
it is rocket science getting 10,000+.

i highly recommend you write your own (it's not that hard), before you 
make impractical demands on websocketd.

aj.

**Comment by jbardu** [comment]
I have a websocket server, using any:event and perl it doesn't have a problem
with client numbers, just it isn't very fast, because the websocket packets and
fragments, are handled at the scripting level.

I wasn't "making impractical demands" just wanted to check what the problem
with doing so might be. Not *please handle 10,000 clients* but *connect direct
to a port rather than fork a child*.

Even without any extra complexity to websocketd, if websocketd can
handle (say) 100 child netcat children, it would be no different to handle 100
connections to one ip+port, Right?

**Comment by asergeyev** [comment]
Well.. Let's try not to get discussion heated up. Everyone from our users has it's needs and goals and would like to have some problems solved in tool they use, websocketd. 

Sometimes, as contributors, we say no to feature requests and that's the case with demuxing.

Demultiplexing was discussed in #50, #84, **#95**, #132; you could comment on the opinions stated there. None of it means it'll be something that will be never added but so far we have agreement of not chasing this feature.

**Comment by jbardu** [comment]
I'm not heated up.

But .. I'm not talking about de-mux. I'm happy you decided not to get into the complexities of that.

I think my request is different.

Lets do an example. Say a resource called "ping" that times pinging. Say I want to support
1000 clients connected to the program "ping". I can let websocketd run 1000 ping programs
(this is not mux/demux) or I can run one ping but it listens on a port, and can accept and
handle 1000 connections (from websocketd).

Obviously the second situation is preferable.
You suggest I can use netcat.

But then I have 1000 netcat processes.

Do you see my question? it isn't issue #50 etc, where everyone is looking at the same thing.

**Comment by asergeyev** [comment]
you asking to get 1 line (every line eventually) from TCP port (or netcat output) and send it to 1000 connected websocketd clients, correct?

**Comment by jbardu** [comment]
No,
I want to have N connections between N clients and one back-end program, that can support N simultaneous open connections.

So each new client gets hooked into 127.0.0.1:80 as a r/w socket, and the program listening there deals with that client directly using event driven I/O (not fork/accept, or threads - anyway doesn't matter the details of how that program works).

**Comment by joewalnes** [comment]
This backing socket feature is something I've pondered. It has a lot of analogies with CGI vs FastCGI in that it avoids having many processes.

Thing is I don't see it actually solving the problem. If you've already got a program that can handle evented I/O from multiple processes then you've already handled the most complicated part. The only thing websocketd brings to the picture is handling the negotiation and message framing. Negotiation may be a tiny bit faster but the actual message processing would likely be slower because of the additional deserialization/transform/serialize step that websocketd adds in to the mix. At the end of the day that backing process is still going to have to produce and consume messages in some form and it the native WebSocket message format is a very lightweight thing to process. It's more likely that the performance issues are in the core event loop rather than the websocket message handling.

**Comment by asergeyev** [comment]
You lost me. 

Client 1 connects to websocketd, upgrades it's HTTP socket to WebSockets protocol; we create env variables, run program or do something else. What happens then?

Later Clients 2-1000 connect... Upgrade their sockets, what happens? Where do we put their environment data, their IP addresses, their HTTP headers? Where do we put their input lines? What guarantees should we make about those input lines from different clients and how do we make sure we never stuck with unread input from those sockets?

Later clients 1-12 and 14-1000 disconnect... What happens?

Few scenarios after:
* Client 13 disconnects.
* Client 13 is not reading what we trying to send to it... but client 1001 connects.
* Program (or socket that we connected to) terminated.
* Program (or socket that we connected to) are not sending any input for hours but not terminated.

**Comment by asergeyev** [comment]
/// deleted my long comment, sorry if you wanted to reply....

I got it now. You're ok with netcat approach just do not like that there should be overhead of netcat. @joewalnes comment helped to figure it out and I have nothing to add.

**Comment by jbardu** [comment]
Exactly.

I don't mind netcat but I don't like there is one netcat process for every concurrent
connected client.

It seems that websocketd can do it, then the advantage is there is only 2 PIDs to
worry about: websocketd, and backend (more if backend is accept/fork, or less if
backend is event driven, doesn't matter).

Sorry if my request wasn't clear I wasn't thinking about mux/de-mux so had to read
about that.

**Comment by jbardu** [comment]
@joewalnes the problem I have found is that the attractive easy-to-use websocket libs for scripting languages appear to be slow. Perhaps because they do the message framing at the interpreter level instead of in C. I don't know.

Either way, I can pump data 40 megabit of data through websocketd to python or perl script without problem, but doing the same thing if the listening process is python + websocket libraries is very slow. A single browser can send many hundred megabit over a websocket, but only if the server is fast.

Just like stunnel4 takes away the https negotiation and connects to a back-end, it seems more natural somehow for websocketd to do that, and less natural for it to be a glorified cgi-bin. Shrug.

Maybe really nginx should just do it natively. Maybe that is the future?

**Comment by joewalnes** [comment]
I hear what you're saying.If websocketd takes care of the websocket protocol, it's still going to have to convert it to another protocol which the backend language must support. Why would that be any faster for the scripting language to process? It would also still have to pass the HTTP headers to the socket otherwise the socket won't know anything about the client or what it's requesting.

**Comment by jbardu** [comment]
I don't know why it is slow, just for me, I found websocketd quicker and easier than "scripting language + web socket library". Most server-side is built to plug and play with ip:port or unix local socket?
Passing headers via environment variables has been insecure in the past, and CGI, one process per client, is a bit old school. Websocketd can just print headers right after it connects, ending in a new line, then, after that, doesn't everything actually get more natural than managing N forked children with reaping, limiting children, and all that stuff? To continue down the cgi path you're re-inventing apache, no? Someone will ask for memory limits, spawning speed limits, are symlinks allowed or not. What about stuck cgi children.
I get back to stunnel example: you have https, you have backend(s) that speak un-encrypted flows. Stunnel does the https negotiation, and then its natural function is to go to ip:port.

Hey its just a suggestion. I expect it will come up as a question again though.

**Comment by joewalnes** [comment]
@jbardu 

There was a lot of content in your last message but I had trouble understanding how it related. Please could you try rephrasing it because I'm still not sure what you're suggesting.

**Comment by jbardu** [comment]
Sure, I can put it in points.
- websocketd is faster than alternatives, but as it is not a component, it can only be used as an end-point in CGI mode
- in this space, supporting ip:port is pretty normal
- handling child processes properly seems more effort than an ip:port feature.
- headers can be sent to a back-end by printing them upon connect

that's basically it.

And then the last part was sort of a reminder that I'm defending the feature as a "natural" one, rather than making a fuss.

**Comment by joewalnes** [comment]
> websocketd is faster than alternatives

Faster than what exactly? 

If you're referring to handling network connections, then that doesn't really help your situation as your backend endpoint needs to handle just as many network connections.

If you're referring to load balancing, then websocketd doesn't do that. You'd need something like Nginx or HAProxy instead and websocketd doesn't add anything.

If you're referring to parsing HTTP headers, then it may be, but it will have to pass them down the connection to the backend which will have re-parse them anyway, so overall it creates additional load.

If you're referring to parsing websocket messages, then the same applies as the headers. The WebSocket message framing protocol is designed to be very lightweight to parse - in fact it should be more efficient than parsing line by line text.

So I still don't see how it improves performance. My recommended alternative is "nothing" (i.e. clients connect direct to your service) which websocketd will always have a larger overhead than.

> but as it is not a component

What do you mean by component? Component in what system?

> it can only be used as an end-point in CGI mode

In the context of this sentence I have no idea what this means.

> in this space, supporting ip:port is pretty normal

Yes! Clients should connect direct to your ip:port, or via a frontend such as Nginx or HAProxy. websocketd adds nothing here.

> handling child processes properly seems more effort than an ip:port feature

Again, I agree. Which is why websocketd has no place in your architecture.

> headers can be sent to a back-end by printing them upon connect

That's how headers will work if you just handle the sockets in your own event loop. Again websocketd doesn't add anything.

I'm closing this issue.

**Comment by asergeyev** [comment]
I support since there is really no clear win over using netcat btw. That program is good and robust, I do not see why our implementation would be much better. Saving not really significant resources is not a goal of websocketd at this moment since desing requires us to load external programs all the time... 

The only better solution for you is still custom code, not something that we may provide.

BTW, I can run 1K netcats on my laptop without observing any reasonable load. I'm lazy not to tune my system to run 10K of them (and careful not to dos something) but I think it's possible too. It's common myth that extra processes create lots of load.  Those loads are small comparing to what systems can do nowadays.
