### ISSUE TITLE
Support for fragmentation ?

### ISSUE THREAD

**Issue by jkh1** [joewalnes/websocketd#171]
Does websocketd support fragmented messages ? Large messages are received correctly by websocketd when sent from Firefox 40.0 but not when sent from Chromium 43.0. As far as I understand Firefox doesn't send fragmented messages whereas Chromium does.

**Comment by asergeyev** [comment]
Yes, this needs to be worked on... 

Current go-net websocket lib does not support it. Ideas on what to do are welcome...  (Improving that go lib is an option to make world a better place)

https://tools.ietf.org/html/rfc6455#section-5.4

It's not easiest rework since current implementation of Hybi set to read frame by frame and return pre-populated Reader but I might be wrong about it and there is an elegant solution that could be as good.

**Comment by garyburd** [comment]
One possible fix is to switch from the x/net/websocket package to the [Gorilla WebSocket package](https://github.com/gorilla/websocket#readme). The Gorilla package handles fragmented messages.

The Gorilla repository includes a simple example showing how to [access a command line program from a WebSocket](https://github.com/gorilla/websocket/tree/master/examples/command).

**Comment by joewalnes** [comment]
+1 for switching to gorilla

**Comment by asergeyev** [comment]
0.3.0 pre-released with gorilla now.

**Comment by asergeyev** [comment]
Anyone knows how to use it from the browser?
