### ISSUE TITLE
README needs section for "building from source"

### ISSUE THREAD

**Issue by asergeyev** [joewalnes/websocketd#176]
There is lot of confusion about our Makefile in root dir.... we probably can get away changing README to have some general notes for those who want to contribute or just try to build binary themselves... See  #175 and it was coming up before in #76

**Comment by joewalnes** [comment]
Agree.

I like having a Makefile because I switch between a lot of technologies and knowing that I can always run "make" and not have to worry about language specific tools makes it easier for me.

However, it goes against principle of least astonishment for the majority of people. I'd be happy for this to be converted to a regular Go project structure and allow users to "go get; go build".

(The Makefile is still useful for releases, but that's out the way of what typical user's see. And TBH, it may be easier to replace the release Makefile with a shell script).

**Comment by asergeyev** [comment]
"go get" already works :) we should just mention it in good place in README :)

**Comment by asergeyev** [comment]
I'll close. Go get is pretty much mainstream way now.
