### ISSUE TITLE
Test with autobahn.ws/testsuite ?

### ISSUE THREAD

**Issue by MidSpeck** [joewalnes/websocketd#188]
Not really an "issue," but I'm looking into WebSocket servers and was wondering how well websocketd handled against things like invalid UTF-8 messages, the client lying about its payload size, etc.

Have you ever run the Autobahn test suite against websocketd?  If so, can we see the results?  "The test suite will check an implementation by doing basic WebSocket conversations, extensive protocol compliance verification and performance and limits testing."

Example report for a bunch of WebSocket servers:
http://autobahn.ws/testsuite/reports/servers/index.html

**Comment by asergeyev** [comment]
I tried it today. Well there is lots of tests and some of them are not quite worth to implement unless people ask (as with compression in #174 )

I wonder what anyone here might think of importance of following to be fixed:
* ping/pongs (we somewhat ignoring those because it's not something you can tell bash script)
* fragmentation (same thing, if we support it we may only spend resources on server side)
* tricky UTF8 cases (not many of them pass but I doubt much would as you rely on external tool like bash script to echo your data without much idea about input encoding)
* couple tricky close test cases (somewhat important but we also did not leak anything)
* websocket compression

**Comment by asergeyev** [comment]
I'm thinking there is not much we will do to specifically address test. I'll close it for now.

"Invalid headers or data will not break the websocketd" is my answer to the original question.
