### ISSUE TITLE
Way to not fork new process

### ISSUE THREAD

**Issue by Genghoidal** [joewalnes/websocketd#201]
I've tried to use this to allow me to view a remote console from an application running on the server however I do not want the application to restart on refresh of a connected browser.

Is there a way to just connect to the output stream of the already running process instead of forking into a new process on connecting a new browser to websocketd?

**Comment by asergeyev** [comment]
Reload in browser closes opened websocket connection, that stops forked program and as soon as Javascript called to open new connection, a command started again.

It's made that way so that every new connection would be in similar condition if it's made from same or from different clients. See also #132 and related.

**Comment by asergeyev** [comment]
you  can reopen if you'd like.
