### ISSUE TITLE
How to force http to https upgrade

### ISSUE THREAD

**Issue by artemkin** [joewalnes/websocketd#206]
I'm running SSL websocketd with static dir.

So, `https://localhost:8888` works fine, but `http://localhost:8888` returns nothing. How can I force client to automatically switch to SSL in such case? I don't want to use additional proxies, because this is the only piece of functionality I miss right now.

Thanks

**Comment by asergeyev** [comment]
Good point. That's missing.  I need to look into go http lib internals about listening non-TLS requests.

**Comment by artemkin** [comment]
Okay, I thought I just can't find this) The library is great, but this minor piece is a bit annoying, especially when http URLs are already cached in browsers.

**Comment by asergeyev** [comment]
Yeah. So far only way to deal with it is to proxy things with external proxy... Will try to get to it soon.

**Comment by asergeyev** [comment]
Will hold on merge for couple days until I have time to make peace with it or someone complains about my code there and I'll force myself to rewrite this addition and surrounding lines.

**Comment by asergeyev** [comment]
@artemkin :

it would not be **possible** to return redirect on same port as one listened as https://. 

It must be two different ports for http and https due to nature of HTTP over TLS. The new feature I added in PR is "--redirectport"   It requires you to enter something else, say "8000" to redirect http://host:8000/ to https://host:8443/
(rational choice for --ssl would be --port 443 --redirport 80)

**Comment by artemkin** [comment]
@asergeyev Thanks! Yes, I see.

It seems the only way is to detect TLS handshake, and redirect to http or https endpoint.

http://stackoverflow.com/questions/22453782/nodejs-http-and-https-over-same-port/23975955

**Comment by asergeyev** [comment]
I don't think there is need to implement that kind of same port to same port redirect. I don't quite see google/facebook/amazon/yahoo doing it on their servers and it's not quite in protocol standard. I'd leave it with two port numbers for now.  Maybe it's just because I don't feel like shimming listener code.

Supporters for adding support for same port HTTP/HTTPS are welcome to add their comments.

**Comment by asergeyev** [comment]
Closing. No real benefit to use same port IMO.. feel free to disagree.
