### ISSUE TITLE
Requiring gems when using websocketd in ruby

### ISSUE THREAD

**Issue by DannyBen** [joewalnes/websocketd#254]
Hi,

I am having difficulties using websoketd with ruby, when my ruby script needs to `require` gems.

I have this sample code saved as `sockets.rb`:

```ruby
#!/usr/bin/env ruby
require 'redis'

STDOUT.sync = true

while true do
  puts Time.now
  sleep 1
end
```

And then I am running this:

```
$ websocketd --loglevel=trace --port=4000 --devconsole $PWD/sockets.rb
```

Then, when accessing the devconsole, and connecting, I get disconnected immediately, and the log is saying `cannot load such file -- redis`.

I should mention that:

1. The redis gem is installed
2. Running `./sockets.rb` works without a problem
3. Removing the `require 'redis'` from the above code works

Any hint as to what may be the cause?

Full log:
```
Thu, 20 Apr 2017 09:16:27 +0000 | ACCESS | session    | url:'http://localhost:4000/' id:'1492679787832320059' remote:'10.0.2.2' command:'/vagrant/ruby/test/websocketd/sockets.rb' origin:'http://localhost:4000' | CONNECT
Thu, 20 Apr 2017 09:16:27 +0000 | ERROR  | stderr     | url:'http://localhost:4000/' id:'1492679787832320059' remote:'10.0.2.2' command:'/vagrant/ruby/test/websocketd/sockets.rb' origin:'http://localhost:4000' pid:'4637' | /home/ubuntu/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- redis (LoadError)
Thu, 20 Apr 2017 09:16:27 +0000 | ERROR  | stderr     | url:'http://localhost:4000/' id:'1492679787832320059' remote:'10.0.2.2' command:'/vagrant/ruby/test/websocketd/sockets.rb' origin:'http://localhost:4000' pid:'4637' |  from /home/ubuntu/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Thu, 20 Apr 2017 09:16:27 +0000 | ERROR  | stderr     | url:'http://localhost:4000/' id:'1492679787832320059' remote:'10.0.2.2' command:'/vagrant/ruby/test/websocketd/sockets.rb' origin:'http://localhost:4000' pid:'4637' |  from /vagrant/ruby/test/websocketd/sockets.rb:2:in `<main>'
Thu, 20 Apr 2017 09:16:27 +0000 | ACCESS | session    | url:'http://localhost:4000/' id:'1492679787832320059' remote:'10.0.2.2' command:'/vagrant/ruby/test/websocketd/sockets.rb' origin:'http://localhost:4000' pid:'4637' | DISCONNECT
```

**Comment by asergeyev** [comment]
Disclaimer I know very little about ruby

I think this is effect of env cleaning to avoid exposing too much info to script which could leak into web. So in order to reverse that you need to run ruby from your local copy yourself (this is where it installs all gems too)... There are two ways: write wrapper that would handle changing env before your program executes (similar way is to give ruby interpreter bunch of params)  or install libs you need globally, without using user-specific ruby lib directories

Following is written with rbenv in mind, if you use other way to handle localized ruby, you'll need to find something else.

I'd say wrapping and running local copy is cleaner so it'll likely be similar to running local ruby from crontab

    /home/username/.rbenv/bin/rbenv exec sockets.rb

As a rough way to make things work you may also try  --passenv PATH since I don't see if rbenv passes any other variable that would affect which ruby install is there.

**Comment by DannyBen** [comment]
I see... I am using RVM.

Is there no way to tell websocketd to avoid altering the environment?

**Comment by asergeyev** [comment]
```--passenv=$(env | sed s/\=.*// | xargs | tr ' ' ,) ```

will work to pass all variables but it has it's performance and security implications so I don't want to implement *
