### ISSUE TITLE
top style output

### ISSUE THREAD

**Issue by aleemb** [joewalnes/websocketd#263]
This is pretty sweet, many thanks for putting this out.

Is it possible to capture the output of `top` today or accepting a new feature request for this? Would be pretty awesome, imho.

**Comment by aleemb** [comment]
To be clear, while it's possible to run `top -n 1` and capture it, I meant more along the lines of capturing any such output (`varnishtop` in particular for my use-case).

**Comment by asergeyev** [comment]
If I'd design an app like this I'd go for intermediate script (in python or perl) that parses output of external commands and gives json as output (with possible caching in shared filestore or memory). Then you can write your javascript part that connects to websocket and waits for those json messages that your server part provides.

**Comment by aleemb** [comment]
@asergeyev Seems like an over-engineered solution and very output-specific so it wouldn't scale across multiple commands.

Far simpler would be to run the curses-based command inside `screen` and capture the output using `hardcopy` and relay that.

However, having this as a feature in websocketsd would kick things up a couple notches. Running curses-style commands like `top` in the browser has a high wow factor and good utility.

**Comment by asergeyev** [comment]
I don't know a terminal emulator for web apps. If one exists you can put websocket into binary mode and pass data from server ncurses app to frontend

**Comment by HarriL** [comment]
We are using the websocketd because it is best and nice, doing its one and only task brilliantly. It is praising the design philosophy of Unix (& Linux) - which is Kiss. This way you do have minimal hassle, bugs and need for support. You shoud add (or create) a preprocessor from top to websocketd. Anyhow after top you shall need connection for watch, sar, etc. We did our own preprocessor for a propriatary SW. It reads heartbeat from the SW and sends JSON to websocketd. Idea is simple and you may pipe or whatever to connect top and wsd.
