### ISSUE TITLE
Pair of websocketd

### ISSUE THREAD

**Issue by limenleap** [joewalnes/websocketd#277]
Hi
I was wondering if I can run one websocketd on one machine at one IP address, and another websocketd on another machine at another IP address -- and push data to and fro. Is this possible? Can I have some starting script for doing this, please?

**Comment by asergeyev** [comment]
In order to talk to websocketd you need a client. So if your client is program running under other websocketd it'll work but seem like there are better ways to solve any problems that possibly solved by doing all this dance.

So I'll leave it hanging for comments but would not personally advise pursuing.
