### ISSUE TITLE
Disconnecting the user

### ISSUE THREAD

**Issue by Sa1ch** [joewalnes/websocketd#282]
Hello! Tell me please, when the user is disconnected, is the message sent to the script? Or you need to constantly listen to the processes?

**Comment by asergeyev** [comment]
Script gets it's STDIN closed and  after some time (100ms + closetime) SIGINT will be sent... If that is caught by script it has 160ms + closetime to terminate or websocketd would follow up with SIGTERM... if that did not help after additional 500 ms + closetime before it would be killed.

SIGINT and SIGTERM is likely noop in Windows. But i'm not sure. Kill uses cross-platform function so it should be working properly.

closetime set by --closems flag in milliseconds

You can catch SIGINT in your script to perform some cleanup tasks. Or, if you passing input to some other process it'll be possible to catch process completion due to lack of STDIN to start cleanup

**Comment by Sa1ch** [comment]
Thank you
