### ISSUE TITLE
Example with colors

### ISSUE THREAD

**Issue by ric79** [joewalnes/websocketd#292]
Hello,
I'm sharing here a bash example with colors. It could be nice for websocketd to be somehow aware of colors...

`websocketd --port=8080  ./countColored.sh`

**countColored.sh:**
```
#!/bin/bash
RED='\033[0;31m'
NC='\033[0m' # No Color

for ((COUNT = 1; COUNT <= 10; COUNT++)); do
  printf "Count ${RED}${COUNT}${NC}\n"
  sleep 1
done
```

**html:**
```
<!DOCTYPE html>
<div id="log"></div>
<script>
  function convertBash(code) {
      dictionary = {
          '\033[0;30m': '<span style="color:black">',
          '\033[0;31m': '<span style="color:red">',
          '\033[0;32m': '<span style="color:green">',
          '\033[0;33m': '<span style="color:yellow">',
          '\033[0;34m': '<span style="color:blue">',
          '\033[0;35m': '<span style="color:purple">',
          '\033[0;36m': '<span style="color:cyan">',
          '\033[0;37m': '<span style="color:white">',
          '\033[0m'    : '</span>'
      }     
      for (var key in dictionary) {
         code = code.replace(key, dictionary[key]);
      }
      return code.replace("\n", "<br>");
  }

  // helper function: log message to screen
  function log(msg) {
    document.getElementById('log').innerHTML  += msg + '<br>';
  }

  // setup websocket with callbacks
  var ws = new WebSocket('ws://localhost:8080/');
  ws.onopen = function() {
    log('CONNECT');
  };
  ws.onclose = function() {
    log('DISCONNECT');
  };
  ws.onmessage = function(event) {
    log('MESSAGE: ' + convertBash(event.data));
  };
</script>
```
Output:
![xx](https://user-images.githubusercontent.com/6887824/36840777-8376c49e-1d46-11e8-95d2-ee127ec8e477.jpg)

**Comment by asergeyev** [comment]
It's a neat example. Only that there are tons of escape codes one would need to implement in order to emulate color terminal properly.

IMO it would be easier for someone to create project based on some JS terminal emulator (maybe https://github.com/Gottox/terminal.js/ and use it as devconsole like debugging tool for websocketd scripts)  I'm against integrating this as standard devconsole because it turns websocketd into terminal emulator rather than simple Websocket server.
