### ISSUE TITLE
Can't CONNECT through router

### ISSUE THREAD

**Issue by samWieczorek** [joewalnes/websocketd#297]
I use websocketd in a local network and it works well. It runs on a RPi A (ip = 192.168.10.76) and I can view the page from a Rpi B (which is also a router).
I want to access page from outside the local network, for which the entry point is the router B.
I have opened the port 9000 on the router  : 
sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 9000 -j DNAT --to 192.168.10.76:9000

From the outside, i can view the page but no connection is made by websocketd : 
websocketd --port=9000 --staticdir=./static python RC.py
Wed, 28 Mar 2018 08:42:06 +0200 | INFO   | server     |  | Serving using application   : /usr/bin/python RC.py
Wed, 28 Mar 2018 08:42:06 +0200 | INFO   | server     |  | Serving static content from : ./static
Wed, 28 Mar 2018 08:42:06 +0200 | INFO   | server     |  | Starting WebSocket server   : ws://rochail:9000/
Wed, 28 Mar 2018 08:42:06 +0200 | INFO   | server     |  | Serving CGI or static files : http://rochail:9000/
Wed, 28 Mar 2018 08:42:09 +0200 | ACCESS | http       | url:'http://mydomain.com:9000/' | STATIC
Wed, 28 Mar 2018 08:42:19 +0200 | ACCESS | http       | url:'http://mydomain.com:9000/' | STATIC

What am I doing wrong ?

Thanks

**Comment by asergeyev** [comment]
https://www.digitalocean.com/community/tutorials/iptables-essentials-common-firewall-rules-and-commands  I recommend info from here and other guides. It's hard to give you recommendations without knowing your network setup and/or current firewall settings.


As websocket log goes it seem to work as designed. Unless your client side asks for protocol upgrade websocketd will not run RC.py. That's why static content is served.
