### ISSUE TITLE
add the ability to disable seesions

### ISSUE THREAD

**Issue by volkovmqx** [joewalnes/websocketd#345]
Hello, 
right now each connection has its own session. this is limiting the features of websockets.
for example right now there is no way to build a chat room, where everyone who is connected receive the same data

**Comment by asergeyev** [comment]
You still can do this with separate sessions. Otherwise it's not websocketd but some other customized WebSockets server you need.

We discussed and killed that idea many times before
https://github.com/joewalnes/websocketd/issues/50

feel free to suggest something but I doubt there is real implementation possible that would satisfy all users.
