### ISSUE TITLE
Is websocketd multi-user ?

### ISSUE THREAD

**Issue by medi-montaseri** [joewalnes/websocketd#374]
I like to use websocketd as an inetd or CGI to launch a process and work as a conduit between client and server (the backend process, not websocketd). what is the high level outline of what I need to do. 

1- Is websocketd multi-user ? i.e does it allow multiple clients to connect and conduct business.
2- What kind of client information is passed from websocketd to execed program ?
3- A use case is where backend process prints logs which I want to convey to client. Given WebSocket notion of messaging (or frames), is there any I/O buffering that I should be concern about.
4- A use case is where backend process ask a question from the user on stout and stdin, again related to I/O buffering, is there any foreseeable issue related to such interactive scenarios ?

Imagine I was trying to solve telnet and ssh with websocket. Am I barking at the wrong tree and should just use ssh and be done.

Thanks
PS: in the  old days, we used Usenet, but now it seems like SCM (like Git) is used for such Q&As. Is this how I should be asking questions from author of a software module ?

**Comment by medi-montaseri** [comment]
Got my first question answered; websocketd is multi-user (aka multi-client)

**Comment by asergeyev** [comment]
Websocket output is line-by-line treated (except binary mode which is not something that would work with server script above).

So when you do `input("hint")`  and there is no linebreak you'll not see message until you enter the value to stdin.

So you probably need   `name = input("enter your name:\n")` and script will start working in devconsole of websocket.


As for your client program... There is no way for websocket to signal that now it's waiting on the input... It's always waiting. So only thing you can do is to send string to ws whenever you found some keyword, e.g. "your name:" string. 

Otherwise your client could be well sending strings all the time and websocket will happily receive them and give to your server script (which would not read those until it waits for the name)...  You can "invalidate" STDIN bytes received prior to your read but it's deeper and deeper into how OS works and I don't want to head in such more and more confusing direction.

General advice instead:  

**Debug your scripts for websocket with devconsole first**, e.g.
    `websocketd --port 8080 --devconsole python script.py` 
     go to http://localhost:8080/ in the browser and play with it.

From there you will have better idea how to write client outside of the browser.

**Comment by medi-montaseri** [comment]
Thank you for clarification. It seems like for my application, I'd need some sort of raw mode messaging (byte by byte) to emulate a telnet or ssh session. I'll think more about this ... 

Thanks again
