### ISSUE TITLE
Example script implementing authentication and channels

### ISSUE THREAD

**Issue by hrst** [joewalnes/websocketd#378]
Thanks for this awesome project, I especially love the simplicity and not having to download dozens of dependencies.

I read the docs and searched through the issues so I know this question has been discussed before (#50, #95, #224), but there is two things I'd need help with:

1. Authentication
I know how to implement a basic authentication in general, but how would it look like within a websocketd command line script? I found this example: https://github.com/joewalnes/websocketd/wiki/PHP
How would I e.g. correctly refuse a client to connect?

2. Channels
I want to build a simple websocket setup, where there are "channels" clients connect to, and when a new message is sent to a channel, only clients subscribed to that channel receive that message.

I understand that the idea behind websocketd is to leave such implementations to the command line script using FIFO, but I could not find any examples that could give me a basic idea of how this could look like for auth and channels. Does anyone here maybe have a link that I missed (PHP would be perfect but any language implementing this would help me a lot)?

 I'd highly appreciate any help!

**Comment by asergeyev** [comment]
1. Your script cannot really refuse to connect. It might be implemented if we go further with Middleware (#141) idea. So in order to "disconnect" right away you can just finish your script (or close STDOUT if your env allows that)

2. Websocketd is very simple tool to redirect output of program into web application. One might build "channels" program and run it behind websocketd but IMO it's easier to write full-fledged service that would do so. I imagine such code would be easier to maintain and distribute too and it's a likely case of using wrong instrument for the job if you go with websocketd.

If you really want it behind websocketd it may be possible to describe for yourself full-fledged message protocol that you intend to have. Try to describe what you imagine a web-app would do in order to "subscribe" to channels? Will it change subscription during connection? Will it send data? Will it stay connected for a long time? Will clients have expectations of security about messages sent and read?  and so on... 

There are backends suitable for this kind of job, only work of the app might be to proxy notes received from websocketd to a backend (e.g. Postgres LISTEN/NOTIFY) but IMO all this sounds rather complex and simple javascript server (like  https://github.com/websockets/ws#simple-server) with state keeping inside of single code might be good alternative.

**Comment by hrst** [comment]
@asergeyev Thank you very much for your reply and help, much appreciated! I will have a look at a websockets/ws. My hope was to find something "simpler" as I thought channels and such are one of the most basic websockets usages, but understand now there is much more that can be done with it, and how websocketd fits into that! Thanks again!
