### ISSUE TITLE
Allow singleton execution of command-line interface programs

### ISSUE THREAD

**Issue by agalazis** [joewalnes/websocketd#84]
In this mode new clients can subscribe to the ouput of the the already running programme rather that running a new instance of it in parallel . (in other words  the server could be able to broadcast the stdout of one instance to all the clients)

**Comment by tehsenaus** [comment]
I would like this feature.

My use case is that I'm wrapping a JMS topic with websocketd, so my Node.js worker processes can consume the data. Said JMS topic only allows one client connection, but I want multiple Node.js worker processes.

Based on my use case, here would be the spec:
- Process starts on first connection, headers of first connection are sent to process
- Process stops when last connection is closed
- No buffering
- Input from any websocket is sent to the process

If this can be done robustly with standard Unix tools then I will do that, but otherwise I might just drop websocketd and implement this directly in Java. That would be a shame though, as websocketd is so elegant!

**Comment by joewalnes** [comment]
@tehsenaus: Your spec you've provided is very specific to your needs. I suggest you implement something specific for your program. Java or Node.js seems like it would be a much better fit for your needs.

**Comment by tehsenaus** [comment]
I thought the spec was quite basic and common sense, and looking at the code it should be easy to implement (piping all web socket endpoints to a single process endpoint? Correct me if I'm wrong).

Like you say, any implementation of this feature won't suit all use cases. I think in this case it's right to do whatever is simplest. Seems a shame to drop websocketd over a small feature.

**Comment by asergeyev** [comment]
It's not easy. Order of messages, blocking on app not responding or not reading input from sockets, timing of simultaneous disconnect of last client and connect of one new one is all not quite easy to deal with. 

Decisions made about those things that fit your usecase would be not a good fit for others... That's why we suggest this should be individual to each user to implement their own vision of multiplexing. 

As workaround you can write from this app to a file and run tail -f of those files under websocketd. But again;  it all depends on your actual data and interaction patterns.

**Comment by tehsenaus** [comment]
The trouble is implementing my own vision of multplexing basically means not using websocketd. I can't see how I would use a ```tail -f``` approach in a robust way - I'd need to deal with starting the process on first connection and closing on last, where the process wouldn't necessarily be a child process of the multiplexer... It all gets very messy.

It seems much more elegant to make this a part of websocketd - processes should really be managed by their parent. It might not work for *all* users, but it might just work for most.

**Comment by tehsenaus** [comment]
I've now ported this to Node.js and added a --singleton flag.

In case anyone else requires the feature, it's here:
https://github.com/tehsenaus/websocketify
